# Generated by Django 3.2.7 on 2021-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christelle', '0002_auto_20211014_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
