# Generated by Django 3.2.7 on 2021-10-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christelle', '0003_alter_about_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='fonction',
        ),
    ]
