# Generated by Django 3.2.7 on 2021-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christelle', '0006_portfolios_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='lien',
            field=models.URLField(),
        ),
    ]
